README.md
Addresses https://github.com/apache/tvm/issues/7991#issuecomment-833752542
=> Clarify process by replacing abandon with postpone

README.md
Based on the two RFCs I've reviewed, there are two points related to the RFC tracking issue that could be improved IMHO.
1. We currently state that the tracking issue should be opened after the RFC PR is merged. However, it means the author needs to file another PR to update the issue link, which seems not necessary to me. As a result, I refined the description, saying that the issue should be opened when the review is nearly done. The reviewer should also remind authors to open a tracking issue and update the link before merging the RFC PR.
2. To better tracking the RFC issues, I created a new label "rfc-tracking". It would be better to add this label to all RFC tracking issues associated with the RFCs proposed here.
=> Update the guideline of RFC tracking issues

rfcs/0008-microtvm-project-api.md
This PR adds an RFC for the Project API ([embryonic discussion](https://discuss.tvm.apache.org/t/tvm-simplifying-the-compiler-interface/8703) - [m2 roadmap item #6](https://discuss.tvm.apache.org/t/tvm-microtvm-m2-roadmap/8821)`). Project API is a plugin-style infrastructure that allows TVM to integrate with a variety of platform-specific build systems. It is particularly useful to allow TVM to build and time operator implementations for non-traditional build platforms (e.g. embedded firmware) under the microTVM effort.
Draft PR: https://github.com/apache/tvm/pull/8380
@mehrdadh @guberti @tqchen @jroesch @tkonolige @csullivan @leandron @u99127 @mousius @giuseros @gromero @stoa @hogepodge
=> Add Project API RFC

README.md
Hi all,
After some discussion, we'd like to propose that RFCs are numbered according to the GitHub PR number. This follows the idea of documenting those RFCs which are rejected. While it adds an extra step to the initial RFC posting, it simplifies all future references by not allocating two different IDs (PR number and RFC number). It also makes it very easy to find the discussion associated with a given PR when viewing it outside of a PR (e.g. through browsing the `tvm-rfcs` repo) and makes for one less link to update.
This also has [precedent](https://github.com/rust-lang/rfcs#what-the-process-is) in the rust community.
Sending this PR as a proposal and would like for everyone to discuss/approve/reject this idea here.
@hogepodge @apache/tvm-committers @tqchen 
-Andrew
=> Update RFC numbering guidance to use PR number

rfcs/add_paddlepaddle_frontend.md
Add a PaddlePaddle frontend for TVM, also I have created [a RFC topic in forum](https://discuss.tvm.apache.org/t/rfc-add-a-paddlepaddle-frontend/10692) where we can discuss at same time.
The related pull request is https://github.com/apache/tvm/pull/8645, still lack of UT, which will be finished in a week.
@tqchen @FrozenGene @junrushao1994 @jcf94
=> [RFC][Frontend] Add a PaddlePaddle Frontend

rfcs/0025-add-pytorch-tvm.md
This RFC add a `PyTorchTVM` module to support: compile TorchScript to TVM and use accelerated module in PyTorch.
Initial PR:  https://github.com/apache/tvm/pull/8777
Discuss: https://discuss.tvm.apache.org/t/rfc-pytorchtvm-compile-torchscript-to-tvm-and-use-accelerated-module-in-pytorch/10873
=> [RFC]PyTorchTVM

rfcs/0036-tvm-script-namespace.md
It's a rfc for changing TVMScript namespace to enable auto-completion support and pass pylint checks.
=> [RFC][TVMScript] New namespace for tvmscript

rfcs/000x-tir-non-scalar-constants.md, rfcs/0022-tir-non-scalar-constants.md
* added the markdown
* added a commit msg header
Change-Id: I0fb3e6b97242ba219c157c9abe5184f14a9f8eff
=> [RFC][TIR] TIR Non-scalar Constants

rfcs/0009_Unified_Static_Memory_Planning.md, rfcs/000y_Unified_Static_Memory_Planning.md
This commits adds the RFC (.md) for USMP.
pre-RFC on discuss : https://discuss.tvm.apache.org/t/rfc-unified-static-memory-planning/10099
=> [RFC] TVM Unified Static Memory Planning

rfcs/0021-tvmc_add_support_for_micro_targets.md
This RFC is about how TVMC (TVM CLI tool) can be extended to support microTVM
targets, considering the variety of platforms supported by microTVM, like Zephyr
and Arduino, and also considering future platforms, taking into account the use
of custom/adhoc platforms provided by users at their convenience.
=> [RFC][TVMC] Add support for micro targets

rfcs/0051-PackedFunc-as-Object.md
Bring `PackedFunc` into TVM Object System
=> Bring `PackedFunc` into TVM Object System

0000-template.md, rfcs/0055-slow-tests.md
Also see discussion in the pre-RFC: https://discuss.tvm.apache.org/t/rfc-ci-skip-slow-tests-on-prs/11910
@areusch @Mousius
=> @slow test RFC

rfcs/0046-module-based-model-runtime-for-aot.md
This adds the RFC for MBMR for AOT. See also discussion on the Discuss forum: https://discuss.tvm.apache.org/t/aot-module-based-model-runtime-interface-for-aot/11068
@tqchen @manupa-arm @jroesch @mehrdadh @csullivan @adstraw @Mousius @kparzysz-quic
=> Module Based Model Runtime for AOT

rfcs/0039-buffer-physical-layout.md, rfcs/XXXX-buffer-physical-layout.md
~~This RFC introduces a hard boundary between the “logical layout” of a mathematical tensor and the “physical layout” of a buffer in memory, along with a specification for defining the conversion between the two.~~
Following discussion, this RFC has been heavily modified to support more flexible layout transformation annotations, not just a single transformation from logical layout to physical layout.
[Rendered markdown link](https://github.com/Lunderberg/tvm-rfcs/blob/data_layout/rfcs/0039-buffer-physical-layout.md)
=> [RFC][TIR] Layout transformations on buffer access

rfcs/0058-replace-codeowners.md
Pre-RFC: https://discuss.tvm.apache.org/t/rfc-remove-codeowners/12095
Related PRs:
- https://github.com/apache/tvm/pull/9934
- https://github.com/apache/tvm/pull/9973
- https://github.com/apache/tvm/pull/10322
- https://github.com/apache/tvm/pull/10208
cc @areusch @jroesch @Mousius
=> Replace codeowners with more relevant automation

rfcs/0009_Unified_Static_Memory_Planning.md
This commit adds a new usecase (U4) for
the USMP that enables the user to place I/O
tensors within the workspace and not
providing them seperately.
This allows the space for I/O tensors to
be utilized by the inference.
=> [USMP] Adding U4 usecase

rfcs/0063-clarifying-buffer-declaration-and-access.md
In https://github.com/apache/tvm/pull/9727 and [RFC#39](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0039-buffer-physical-layout.md), we deprecated Load and Store to use BufferLoad and BufferStore instead in order to support generalized multi-dimensional physical buffer access. This is a follow-up that documents necessary clarifications, implications about the new buffer convention, as well as the post-hoc pass checklist.
Rendered version: https://github.com/vinx13/tvm-rfcs/blob/clarify-buffer-access/rfcs/0063-clarifying-buffer-declaration-and-access.md
cc @tqchen @Lunderberg @junrushao1994 @csullivan @mbs-octoml  @jroesch @areusch @wrongtest @Hzfengsy
=> RFC: clarifying buffer declaration and access

rfcs/0069-relax-roadmap.md
=> [RFC] Relay Next Roadmap

0067-quarterly-releases.md, rfcs/0067-quarterly-releases.md
Cross-posted to discuss here: https://discuss.tvm.apache.org/t/rfc-quarterly-releases/12629
cc @areusch @leandron @Mousius
=> [RFC] Quarterly Releases

rfcs/0076_mlf_with_multiple_modules.md
This RFC proposes adding multiple module support in Model Library Format.
cc @gromero @areusch
=> [RFC][MLF] Model Library Format with Multiple Modules

rfcs/0070-introducing-decl-buffer.md
This is a follow-up of https://github.com/apache/tvm/pull/9727 and [RFC#63](https://github.com/apache/tvm-rfcs/pull/63). Currently buffer can be implicitly declared and then used. The implicit behavior can be error prone and makes analysis more difficult. This RFC introduces `DeclBuffer`, a new IR construct as an explicit statement for buffer declaration.
Rendered version: https://github.com/vinx13/tvm-rfcs/blob/decl-buffer/rfcs/0070-introducing-decl-buffer.md
cc @tqchen @Lunderberg @junrushao1994 @csullivan @mbs-octoml @jroesch @areusch @wrongtest @Hzfengsy
=> [RFC] Introducing DeclBuffer

rfcs/0080-llvm-target.md
Follow-up to https://discuss.tvm.apache.org/t/modularizing-llvm-codegen-jit/12764
=> [RFC] Create LLVM scope class for use with LLVM libraries

rfcs/0077-layout-transform-padding.md, rfcs/XXXX-layout-transform-padding.md
This RFC introduces a method to specify padding to be applied as part of a buffer layout transformation, to be used when the desired layout does not evenly tile the buffer being transformed, and simplifications that can be performed based on these padded buffers.
The motivating examples are primarily in the "Implementation options" section, which goes through several desired usages of the buffer padding, and how they can be automatically derived using the TIR primitives/transformations described in earlier sections.
[Rendered Markdown link](https://github.com/Lunderberg/tvm-rfcs/blob/buffer_layout_padding/rfcs/0077-layout-transform-padding.md)
=> [RFC] Buffer Layout Padding

rfcs/0070-introducing-decl-buffer.md
As a followup on the previous discussion https://github.com/apache/tvm-rfcs/pull/70#issuecomment-1149308146, this PR updated the DeclBuffer RFC with TVMScript related changes.
cc @Lunderberg @wrongtest-intellif @Hzfengsy @junrushao1994 @cyx-6 @tqchen
=> Amend RFC0070 with DeclBuffer TVMScript syntax updates

rfcs/0088-commit-message-guideline.md
This RFC proposes adding a Commmit Message Guideline to Apache TVM
documentation to help guide contributors on how to write good commit
messages when submitting code / Pull Requests.
Co-authored-by: Leandro Nunes <leandro.nunes@arm.com>
=> [RFC] Add Commit Message Guideline

rfcs/0097-unify-packed-and-object.md
This RFC proposes to further unify our PackedFunc and Object in TVM Runtime. The proposal builds on top of our past lessons and recont lessons from related project such as [matxscript](https://github.com/bytedance/matxscript)
The key improvements include: unifying type_code, solidifying AnyValue support for both stack and object values, open doors for small-string and NLP-preprocessing, and enable universal container.
[rendered](https://github.com/tqchen/tvm-rfcs/blob/unify-packed/rfcs/0097-unify-packed-and-object.md)
=> [RFC] Further Unify Packed and Object in TVM Runtime

rfcs/0099-improve-IntSet-representation.md, rfcs/0099-introduce-PresburgerSet.md
This RFC proposes to introduce PresburgerSet as another integer set utility, aiming to tackle more complex analysis problems.
[rendered](https://github.com/multiverstack-intellif/tvm-rfcs/blob/improve_intset/rfcs/0099-introduce-PresburgerSet.md)
cc @wrongtest-intellif @Hzfengsy @spectrometerHBH @tqchen
=> [RFC] Introduce PresburgerSet

rfcs/0100-sparestir-dialect.md
This RFC proposes a plan for integrating SparseTIR as a new dialect into TVM.
- [rendered](https://github.com/yzh119/tvm-rfcs/blob/main/rfcs/0100-sparestir-dialect.md)
- [discussion thread](https://discuss.tvm.apache.org/t/rfc-sparsetir-as-a-new-dialect-in-tvm/14645)
=> [RFC] SparseTIR Dialect

rfcs/0102-clarify-strategy-decision-process.md
- [rendered](https://github.com/tqchen/tvm-rfcs/blob/strategy/rfcs/0102-clarify-strategy-decision-process.md)
=> [Process RFC] Clarify Community Strategy Decision Process

rfcs/0104-scalable-vectors-in-tir.md
This RFC is to add support for vector length agnostic programming in TVM stack.
=> [RFC] Scalable vectors in TIR

rfcs/0107-scalable-matrix-extension-enablement.md
A RFC for enabling Scalable Matrix Extension code generation in TVM.
[Rendered](https://github.com/apache/tvm-rfcs/blob/049662ddcd21636eedc2d7dae32403c3238d9fd9/rfcs/0106-scalable-matrix-extension-enablement.md)
=> [RFC] Scalable Matrix Extension enablement

0108-add-nnef-frontend.md, rfcs/0108-add-nnef-frontend.md
A RFC to add a Neural Network Exchange Format frontend to TVM relay. 
[Link to discuss](https://discuss.tvm.apache.org/t/rfc-0108-add-nnef-frontend/17088)
=> [RFC] Add NNEF frontend
